name: 'ecommerce_analytics'
version: '1.0.0'
config-version: 2

# Profile configuration
profile: 'ecommerce_analytics'

# Model paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Clean targets
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

# Documentation
docs-paths: ["docs"]

# Variables
vars:
  start_date: '2023-01-01'
  
# Model configurations
models:
  ecommerce_analytics:
    # Staging models (Silver layer)
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]
      
    # Intermediate models
    intermediate:
      +materialized: ephemeral
      +tags: ["intermediate"]
      
    # Marts (Gold layer)
    marts:
      +materialized: table
      +schema: marts
      +tags: ["marts"]
      
      core:
        +tags: ["core"]
        
      marketing:
        +tags: ["marketing"]
        
      finance:
        +tags: ["finance"]

# Seeds configuration
seeds:
  ecommerce_analytics:
    +schema: seeds
    +tags: ["seeds"]

# Snapshots configuration
snapshots:
  ecommerce_analytics:
    +target_schema: snapshots
    +strategy: timestamp
    +unique_key: id
    +updated_at: updated_at
    +tags: ["snapshots"]

# Tests
tests:
  ecommerce_analytics:
    +store_failures: true
    +schema: dbt_test_failures

# Exposures
exposure-paths: ["models/exposures"]

# Quoting
quoting:
  database: false
  schema: false
  identifier: false

# Dispatch
dispatch:
  - macro_namespace: dbt
    search_order: ['ecommerce_analytics', 'dbt']
