version: 2

models:
  - name: stg_orders
    description: Staging table for orders - cleaned and standardized
    columns:
      - name: order_id
        description: Primary key for orders
        tests:
          - unique
          - not_null
      
      - name: customer_id
        description: Foreign key to customers
        tests:
          - not_null
      
      - name: order_date
        description: Date when order was placed
        tests:
          - not_null
      
      - name: order_status
        description: Normalized order status
        tests:
          - not_null
          - accepted_values:
              values: ['pending', 'processing', 'completed', 'cancelled', 'refunded']
      
      - name: total_amount
        description: Total order amount including all fees
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

  - name: stg_customers
    description: Staging table for customers - cleaned and standardized
    columns:
      - name: customer_id
        description: Primary key for customers
        tests:
          - unique
          - not_null
      
      - name: email
        description: Customer email
        tests:
          - unique
          - not_null
      
      - name: full_name
        description: Customer full name
        tests:
          - not_null
      
      - name: customer_status
        description: Customer account status
        tests:
          - accepted_values:
              values: ['active', 'inactive', 'unknown']

  - name: stg_products
    description: Staging table for products - cleaned and standardized
    columns:
      - name: product_id
        description: Primary key for products
        tests:
          - unique
          - not_null
      
      - name: product_name
        description: Product name
        tests:
          - not_null
      
      - name: price
        description: Product price
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      
      - name: cost
        description: Product cost
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      
      - name: stock_level
        description: Stock availability level
        tests:
          - accepted_values:
              values: ['high', 'medium', 'low', 'out_of_stock']
